source:
  - file: decision_tree_1.yaml
  - file: decision_tree_2.yaml
  - file: decision_tree_3.yaml
commands:
  - !select
    select:
      - !fromSelection
        from: params
        keys:
          - name: criterion
            rename: Criterion
          - name: splitter
            rename: Splitter
          - name: ccp_alpha
            rename: CPP Alpha
          - name: min_samples_split
            rename: Min Samples Split

      - !metadataSelection
        metadata: filename
        rename: File

  - !merge
    merge:
      - sources:
          - decision_tree_1.yaml
          - decision_tree_2.yaml
          - decision_tree_3.yaml
        target: result

target:
  - file: output.csv
    table: result