source:
  - file: decision_tree_1.yaml
  - file: decision_tree_2.yaml
  - file: decision_tree_3.yaml
commands:
  - !select
    select:
      - !fromSelection
        from: params
        keys:
          - name: criterion
            rename: Criterion
          - name: splitter
            rename: Splitter

      - !metadataSelection
        metadata: filename
        rename: Filename

  - !merge
    merge:
      - sources:
          - table_1
          - table_2
          - table_3
        target: table_4

target:
  - file: output.csv
    table: table_4