source:
  - file: data/vitis-report.xml
commands:
  - !select
    select:
      - !fromSelection
        from: profile.AreaEstimates
        keys:
          - name: Resources
            rename: Resources

      - !metadataSelection
        metadata: filename
        rename: File

  - !merge
    merge:
      - sources:
          - vitis-report.xml
        target: result

target:
  - file: output.csv
    table: result